version: '3.4'

x-healthcheck: &healthcheck
  test: [ "CMD", "curl", "-sf", "http://localhost:8545" ]
  interval: 5s
  timeout: 5s
  retries: 3
  start_period: 30s

services:
  # this is a helper service used because there's no official hardhat image
#  l1_chain:
#    image: mantlenetworkio/hardhat:${DOCKER_TAG_HARDHAT:-latest}
#    build:
#      context: ./docker/hardhat
#      dockerfile: Dockerfile
#    env_file:
#      - ./envs/l1_chain.env
#    ports:
#      # expose the service to the host for integration testing
#      - ${L1CHAIN_HTTP_PORT:-9545}:8545
#    volumes:
#      - ./data/l1_chain:/root/.ethereum/geth/
#    healthcheck:
#      <<: *healthcheck
#      test: [ "CMD", "wget", "-qO-", "http://localhost:8545" ]
#
#  deployer:
#    depends_on:
#      - l1_chain
#    build:
#      context: ..
#      dockerfile: ./ops/docker/Dockerfile.packages
#      target: deployer
#    image: mantlenetworkio/deployer:${DOCKER_TAG_DEPLOYER:-latest}
#    entrypoint: ./deployer.sh
#    environment:
#      # Env vars for the deployment script.
#      CONTRACTS_RPC_URL: http://172.17.0.1:9545
#      SKIP_CONTRACT_DEPLOY: ${SKIP_CONTRACT_DEPLOY:-YES}
#      CONTRACTS_DEPLOYER_KEY: '0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97'
#      CONTRACTS_TARGET_NETWORK: 'local'
#    ports:
#      # expose the service to the host for getting the contract addrs
#      - ${DEPLOYER_PORT:-8080}:8081
#    healthcheck:
#      <<: *healthcheck
#      test: [ "CMD", "curl", "-sf", "http://localhost:8081" ]

  dtl:
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.packages
      target: data-transport-layer
    image: mantlenetworkio/data-transport-layer:${DOCKER_TAG_DATA_TRANSPORT_LAYER:-latest}
    # override with the dtl script and the env vars required for it
    entrypoint: ./dtl.sh
    env_file:
      - ./envs/dtl.env
    # set the rest of the env vars for the network which do not
    # depend on the docker-compose setup
    environment:
      # used for setting the address manager address
      URL: http://172.17.0.1:8080/addresses.json
      # connect to the 2 layers
      DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: http://172.17.0.1:9545
      DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT: http://scheduler:8545
      DATA_TRANSPORT_LAYER__SYNC_FROM_L2: 'true'
      DATA_TRANSPORT_LAYER__L2_CHAIN_ID: 17
    ports:
      - ${DTL_PORT:-7878}:7878


  relayer:
    deploy:
      replicas: 0
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.packages
      target: message-relayer
    image: mantlenetworkio/message-relayer:${DOCKER_TAG_MESSAGE_RELAYER:-latest}
    entrypoint: ./relayer.sh
    environment:
      MESSAGE_RELAYER__L1_RPC_PROVIDER: http://172.17.0.1:9545
      MESSAGE_RELAYER__L2_RPC_PROVIDER: http://scheduler:8545
      MESSAGE_RELAYER__L1_WALLET: '0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97'
      RETRIES: 60

  replica_healthcheck:
    depends_on:
      - scheduler
      - replica1
    deploy:
      replicas: 0
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.packages
      target: replica-healthcheck
    image: mantlenetworkio/replica-healthcheck:${DOCKER_TAG_REPLICA_HEALTHCHECK:-latest}
    environment:
      HEALTHCHECK__REFERENCE_RPC_PROVIDER: http://scheduler:8545
      HEALTHCHECK__TARGET_RPC_PROVIDER: http://replica:8545
    ports:
      - ${HEALTHCHECK_HTTP_PORT:-7300}:7300

  integration_tests:
    deploy:
      replicas: 0
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.packages
      target: integration-tests
    image: mantlenetworkio/integration-tests:${DOCKER_TAG_INTEGRATION_TESTS:-latest}
    entrypoint: ./integration-tests.sh
    environment:
      L1_URL: http://172.17.0.1:9545
      L2_URL: http://scheduler:8545
      HEALTHCHECK_URL: http://replica_healthcheck:7300/metrics
      REPLICA_URL: http://replica:8545
      VERIFIER_URL: http://verifier:8545
      URL: http://172.17.0.1:8080/addresses.json
      ENABLE_GAS_REPORT: 1
      NO_NETWORK: 1
      BATCH_SUBMITTER_SEQUENCER_BATCH_TYPE: ${BATCH_SUBMITTER_SEQUENCER_BATCH_TYPE:-zlib}


  gas_oracle:
    build:
      context: ..
      dockerfile: ./gas-oracle/Dockerfile
    image: mantlenetworkio/gas-oracle:${DOCKER_TAG_GAS_ORACLE:-latest}
    environment:
      GAS_PRICE_ORACLE_ETHEREUM_HTTP_URL: http://172.17.0.1:9545
      GAS_PRICE_ORACLE_LAYER_TWO_HTTP_URL: http://scheduler:8545
      BYBIT_BACKEND_URL: https://api.bybit.com
      TOKEN_PRICER_UPDATE_FREQUENCY: 3
      GAS_PRICE_ORACLE_PRIVATE_KEY: '0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba'
      GAS_PRICE_ORACLE_ENABLE_L2_GAS_PRICE: 'false'
      GAS_PRICE_ORACLE_ENABLE_L1_BASE_FEE: 'true'
      GAS_PRICE_ORACLE_TRANSACTION_GAS_PRICE: 0


  batch_submitter:
    depends_on:
      - scheduler
    build:
      context: ..
      dockerfile: ./batch-submitter/Dockerfile
    image: mantlenetworkio/batch-submitter:${DOCKER_TAG_BATCH_SUBMITTER:-latest}
    entrypoint: ./batch-submitter.sh
    env_file:
      - ./envs/batch-submitter.env
    environment:
      L1_ETH_RPC: http://172.17.0.1:9545
      L2_ETH_RPC: http://scheduler:8545
      TSS_CLIENT_RPC: http://localhost:8080
      URL: http://172.17.0.1:8080/addresses.json
      BATCH_SUBMITTER_SEQUENCER_PRIVATE_KEY: ${BATCH_SUBMITTER_SEQUENCER_PRIVATE_KEY:-0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d}
      BATCH_SUBMITTER_PROPOSER_PRIVATE_KEY: ${BATCH_SUBMITTER_PROPOSER_PRIVATE_KEY:-0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a}
      BATCH_SUBMITTER_SEQUENCER_BATCH_TYPE: ${BATCH_SUBMITTER_SEQUENCER_BATCH_TYPE:-zlib}

  fault_detector:
    depends_on:
      - scheduler
    deploy:
      replicas: 0
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.packages
      target: fault-detector
    image: mantlenetworkio/fault-detector:${DOCKER_TAG_FAULT_DETECTOR:-latest}
    entrypoint: ./detector.sh
    environment:
      FAULT_DETECTOR__L1_RPC_PROVIDER: http://172.17.0.1:9545
      FAULT_DETECTOR__L2_RPC_PROVIDER: http://scheduler:8545
      RETRIES: 60


  scheduler:
    depends_on:
      - dtl
    build:
      context: ..
      dockerfile: ./l2geth/Dockerfile
    image: mantlenetworkio/l2geth:${DOCKER_TAG_L2GETH:-latest}
    # override with the geth script and the env vars required for it
    entrypoint: sh ./geth.sh
    env_file:
      - ./envs/geth.env
    volumes:
      - ./chaindata/scheduler/geth:/root/.ethereum/geth/
    environment:
      ETH1_HTTP: http://172.17.0.1:9545
      SEQUENCER_L1_RPC: http://172.17.0.1:9545
      ROLLUP_TIMESTAMP_REFRESH: 5s
      ROLLUP_STATE_DUMP_PATH: http://172.17.0.1:8080/state-dump.latest.json
      # connecting to the DTL
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      # no need to keep this secret, only used internally to sign blocks
      BLOCK_SIGNER_KEY: 'ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'
      BLOCK_SIGNER_ADDRESS: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
      BLOCK_SCHEDULER_ADDRESS: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
      SEQUENCER_CONTRACT_ADDRESS: '0xBe0F340075060F856612d91e17cAe599dE92C745'
      ROLLUP_ENFORCE_FEES: ${ROLLUP_ENFORCE_FEES:-false}
      ROLLUP_FEE_THRESHOLD_DOWN: 0.9
      ROLLUP_FEE_THRESHOLD_UP: 1.1
      GASPRICE: 0
      VERBOSITY: 3
      NAT: 'extip:172.17.0.1'
      IS_SCHEDULER: 'true'
    ports:
      - ${L2GETH_HTTP_PORT:-8545}:8545
      - ${L2GETH_WS_PORT:-8546}:8546
      - ${L2GETH_P2P_PORT:-30303}:30303
    healthcheck: *healthcheck


  sequencer1:
    depends_on:
      - scheduler
    deploy:
      replicas: 0
    build:
      context: ..
      dockerfile: ./l2geth/Dockerfile
    image: mantlenetworkio/l2geth:${DOCKER_TAG_L2GETH:-latest}
    entrypoint: sh ./geth.sh
    env_file:
      - ./envs/geth.env
    volumes:
      - ./chaindata/sequencer1/geth:/root/.ethereum/geth/
    environment:
      ETH1_HTTP: http://172.17.0.1:9545
      SEQUENCER_L1_RPC: http://172.17.0.1:9545
      ROLLUP_TIMESTAMP_REFRESH: 5s
      ROLLUP_STATE_DUMP_PATH: http://172.17.0.1:8080/state-dump.latest.json
      # connecting to the DTL
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      # no need to keep this secret, only used internally to sign blocks
      BLOCK_SIGNER_KEY: '5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a'
      BLOCK_SIGNER_ADDRESS: '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC'
      BLOCK_SCHEDULER_ADDRESS: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
      SEQUENCER_CONTRACT_ADDRESS: '0xBe0F340075060F856612d91e17cAe599dE92C745'
      ROLLUP_ENFORCE_FEES: ${ROLLUP_ENFORCE_FEES:-false}
      ROLLUP_FEE_THRESHOLD_DOWN: 0.9
      ROLLUP_FEE_THRESHOLD_UP: 1.1
      IS_SEQUENCER: 'true'
      P2P_PORT: 30313
      NAT: 'extip:172.17.0.1'
      CONFIG_PATH: ''
      SCHEDULER_P2P_ENODE: 'enode://09998ab210032351a2bea94fbb8c867cfc95553019d3cecfe0d3f3aef78b24290e624b07a99fdaa3c2fb9015d193303179b396e3520284d249ef9a233a5f5e62@172.17.0.1:30303?discport=0'
    ports:
      - ${L2GETH_HTTP_PORT:-7545}:8545
      - ${L2GETH_WS_PORT:-7546}:8546
      - ${L2GETH_P2P_PORT:-30313}:30313
    healthcheck: *healthcheck

  sequencer2:
    depends_on:
      - scheduler
    deploy:
      replicas: 0
    build:
      context: ..
      dockerfile: ./l2geth/Dockerfile
    image: mantlenetworkio/l2geth:${DOCKER_TAG_L2GETH:-latest}
    entrypoint: sh ./geth.sh
    env_file:
      - ./envs/geth.env
    volumes:
      - ./chaindata/sequencer2/geth:/root/.ethereum/geth/
    environment:
      ETH1_HTTP: http://172.17.0.1:9545
      SEQUENCER_L1_RPC: http://172.17.0.1:9545
      ROLLUP_TIMESTAMP_REFRESH: 5s
      ROLLUP_STATE_DUMP_PATH: http://172.17.0.1:8080/state-dump.latest.json
      # connecting to the DTL
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      # no need to keep this secret, only used internally to sign blocks
      BLOCK_SIGNER_KEY: '59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d'
      BLOCK_SIGNER_ADDRESS: '0x70997970C51812dc3A010C7d01b50e0d17dc79C8'
      BLOCK_SCHEDULER_ADDRESS: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
      SEQUENCER_CONTRACT_ADDRESS: '0xBe0F340075060F856612d91e17cAe599dE92C745'
      ROLLUP_ENFORCE_FEES: ${ROLLUP_ENFORCE_FEES:-false}
      ROLLUP_FEE_THRESHOLD_DOWN: 0.9
      ROLLUP_FEE_THRESHOLD_UP: 1.1
      IS_SEQUENCER: 'true'
      P2P_PORT: 30323
      CONFIG_PATH: ''
      SCHEDULER_P2P_ENODE: 'enode://09998ab210032351a2bea94fbb8c867cfc95553019d3cecfe0d3f3aef78b24290e624b07a99fdaa3c2fb9015d193303179b396e3520284d249ef9a233a5f5e62@172.17.0.1:30303?discport=0'
      NAT: 'extip:172.17.0.1'
    ports:
      - ${L2GETH_HTTP_PORT:-7543}:8545
      - ${L2GETH_WS_PORT:-7544}:8546
      - ${L2GETH_P2P_PORT:-30323}:30323
    healthcheck: *healthcheck

  replica1:
    depends_on:
      - dtl
      - scheduler
    # deploy:
    #   replicas: 1
    build:
      context: ..
      dockerfile: ./l2geth/Dockerfile
    image: mantlenetworkio/l2geth:${DOCKER_TAG_L2GETH:-latest}
    entrypoint: sh ./geth.sh
    env_file:
      - ./envs/geth.env
    environment:
      ETH1_HTTP: http://172.17.0.1:9545
      SEQUENCER_L1_RPC: http://172.17.0.1:9545
      SEQUENCER_CLIENT_HTTP: http://scheduler:8545
      ROLLUP_STATE_DUMP_PATH: http://172.17.0.1:8080/state-dump.latest.json
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      BLOCK_SIGNER_KEY: '6395a7c842a08515961888d21d72f409b61fbce96af1e520384e375f301a8297'
      BLOCK_SIGNER_ADDRESS: '0xCd0B4E309FB855d644bA64E5fb3dC3DD08f13917'
      BLOCK_SCHEDULER_ADDRESS: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
      SEQUENCER_CONTRACT_ADDRESS: '0xBe0F340075060F856612d91e17cAe599dE92C745'
#      ROLLUP_BACKEND: 'l2'
      ROLLUP_VERIFIER_ENABLE: 'false'
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      VERBOSITY: 3
      IS_SEQUENCER: 'false'
    ports:
      - ${REPLICA_HTTP_PORT:-8549}:8545
      - ${REPLICA_WS_PORT:-8550}:8546


  replica2:
    depends_on:
      - dtl
      - scheduler
    # deploy:
    #   replicas: 1
    build:
      context: ..
      dockerfile: ./l2geth/Dockerfile
    image: mantlenetworkio/l2geth:${DOCKER_TAG_L2GETH:-latest}
    entrypoint: sh ./geth.sh
    env_file:
      - ./envs/geth.env
    environment:
      ETH1_HTTP: http://172.17.0.1:9545
      SEQUENCER_L1_RPC: http://172.17.0.1:9545
      SEQUENCER_CLIENT_HTTP: http://scheduler:8545
      ROLLUP_STATE_DUMP_PATH: http://172.17.0.1:8080/state-dump.latest.json
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      BLOCK_SIGNER_KEY: '6395a7c842a08515961888d21d72f409b61fbce96af1e520384e375f301a8297'
      BLOCK_SIGNER_ADDRESS: '0xCd0B4E309FB855d644bA64E5fb3dC3DD08f13917'
      BLOCK_SCHEDULER_ADDRESS: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
      SEQUENCER_CONTRACT_ADDRESS: '0xBe0F340075060F856612d91e17cAe599dE92C745'
      ROLLUP_BACKEND: 'l2'
      ROLLUP_VERIFIER_ENABLE: 'false'
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      VERBOSITY: 3
      IS_SEQUENCER: 'false'
    ports:
      - ${REPLICA_HTTP_PORT:-8551}:8545
      - ${REPLICA_WS_PORT:-8552}:8546


  verifier:
    depends_on:
      - dtl
      - scheduler
    # deploy:
    #   replicas: 1
    build:
      context: ..
      dockerfile: ./l2geth/Dockerfile
    image: mantlenetworkio/l2geth:${DOCKER_TAG_L2GETH:-latest}
    entrypoint: sh ./geth.sh
    env_file:
      - ./envs/geth.env
    volumes:
      - ./data/verifier:/root/.ethereum/geth/
    environment:
      ETH1_HTTP: http://172.17.0.1:9545
      SEQUENCER_L1_RPC: http://172.17.0.1:9545
      SEQUENCER_CLIENT_HTTP: http://scheduler:8545
      ROLLUP_STATE_DUMP_PATH: http://172.17.0.1:8080/state-dump.latest.json
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      BLOCK_SIGNER_KEY: '6395a7c842a08515961888d21d72f409b61fbce96af1e520384e375f301a8297'
      BLOCK_SIGNER_ADDRESS: '0xCd0B4E309FB855d644bA64E5fb3dC3DD08f13917'
      BLOCK_SCHEDULER_ADDRESS: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
      SEQUENCER_CONTRACT_ADDRESS: '0xBe0F340075060F856612d91e17cAe599dE92C745'
      ROLLUP_BACKEND: 'l1'
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      VERBOSITY: 3
      ROLLUP_VERIFIER_ENABLE: 'true'
      IS_SEQUENCER: 'false'
    ports:
      - ${VERIFIER_HTTP_PORT:-8547}:8545
      - ${VERIFIER_WS_PORT:-8548}:8546
