
x-healthcheck: &healthcheck
  test: [ "CMD", "curl", "-sf", "http://localhost:8545" ]
  interval: 5s
  timeout: 5s
  retries: 3
  start_period: 30s



services:
  # this is a helper service used because there's no official hardhat image
  l1_chain:
    image: mantlenetworkio/hardhat:${DOCKER_TAG_HARDHAT:-latest}
    build:
      context: ./docker/hardhat
      dockerfile: Dockerfile
    env_file:
      - ./envs/l1_chain.env
    container_name: bitl1chain
    ports:
      # expose the service to the host for integration testing
      - ${L1CHAIN_HTTP_PORT:-9545}:8545
    volumes:
      - ./data/l1_chain:/root/.ethereum/geth/
    healthcheck:
      <<: *healthcheck
      test: [ "CMD", "wget", "-qO-", "http://localhost:8545" ]

  deployer:
    depends_on:
      - l1_chain
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.packages
      target: deployer
    image: mantlenetworkio/deployer:${DOCKER_TAG_DEPLOYER:-latest}
    entrypoint: ./deployer.sh
    container_name: bitdeployer
    environment:
      CONTRACTS_RPC_URL: ${CONTRACTS_RPC_URL:-http://l1_chain:8545}
      CONTRACTS_DEPLOYER_KEY: ${CONTRACTS_DEPLOYER_KEY:-0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97}
      CONTRACTS_TARGET_NETWORK: ${CONTRACTS_TARGET_NETWORK:-local}
      BVM_SEQUENCER_ADDRESS: ${BVM_SEQUENCER_ADDRESS:-}
      BVM_PROPOSER_ADDRESS: ${BVM_PROPOSER_ADDRESS:-}
      BVM_BLOCK_SIGNER_ADDRESS: ${BVM_BLOCK_SIGNER_ADDRESS:-}
      BVM_FEE_WALLET_ADDRESS: ${BVM_FEE_WALLET_ADDRESS:-}
      SKIP_CONTRACT_DEPLOY: ${SKIP_CONTRACT_DEPLOY:-NO}
      BVM_ADDRESS_MANAGER_OWNER: ${BVM_ADDRESS_MANAGER_OWNER:-}
      BVM_GAS_PRICE_ORACLE_OWNER: ${BVM_GAS_PRICE_ORACLE_OWNER:-}
      L1_BIT_ADDRESS: ${L1_BIT_ADDRESS:-0x1A4b46696b2bB4794Eb3D4c26f1c55F9170fa4C5}
    ports:
      # expose the service to the host for getting the contract addrs
      - ${DEPLOYER_PORT:-8080}:8081
    healthcheck:
      <<: *healthcheck
      test: [ "CMD", "curl", "-sf", "http://localhost:8081" ]
